name: Daily Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create data.js if not exists
        run: |
          if [ ! -f data.js ]; then
            echo "var archiveData = {};" > data.js
          fi
      - name: Update Report
        run: |
          cat <<EOT > today.js
    "2026-03-31": {
        "issue": "NO.33 (Clean Start)",
        "main": { "brand": "K-Car", "title": "케이카 C2C 서비스 공식 오픈", "link": "https://www.kcar.com" },
        "ai": [], "auto": []
    },
EOT
          sed -i '/var archiveData = {/r today.js' data.js
      - name: Push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update 2026-03-31" || echo "No changes"
          git push
