name: final
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: add new data
        run: |
          echo '    "2026-04-02": {"issue": "NO.35 (Safe Mode)", "main": {"brand": "테스트", "title": "데이터 누적 성공", "link": "#"}, "ai": [], "auto": []},' > new_data.txt
          sed -i '/var archiveData = {/r new_data.txt' data.js
      
      - name: push to github
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add data.js
          git commit -m "Safe Update" || exit 0
          git push origin main
