name: final
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: update data
        run: |
          echo 'var archiveData = {"2026-04-01": {"issue": "NO.34 (Netlify)", "main": {"brand": "현대차", "title": "현대차그룹 SDV 가속화", "link": "https://www.autodaily.co.kr"}, "ai": [], "auto": []}};' > data.js
      
      - name: push
        run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add data.js
          git commit -m "Update" || exit 0
          git push origin main
